FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.prod.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY server.py .

# Run
EXPOSE 8001
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001"]
